image: samueldebruyn/debian-git

stages:
  - deploy

Mirror to GitHub:
  stage: deploy
  tags:
    - linux
  script:
    - /usr/bin/git push --prune https://$GITHUB_USER:$GITHUB_PASS@github.com/daemondazz/homeassistant-displays.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
